#pragma once
#include "CoreMinimal.h"
#include "EActionType.generated.h"

UENUM(BlueprintType)
enum class EActionType : uint8 {
    None,
    Lock,
    Unlock,
    MakePrivate,
    MakePrivateWithPrompt,
    MakePublic,
    Package,
    Unpackage,
    PackageShippable,
    UnpackageShippable,
    SetSpawn,
    SubmitItemsToStockpile,
    SubmitShippablesToStockpile,
    SubmitStarterKit,
    SubmitLargeItem,
    SubmitVehicle,
    BuildRocket,
    EnterRocketCode,
    ViewLog,
    ViewRegionLog,
    ViewTechTree,
    StopRefueling,
    ChangeFuel,
    SubmitPatients,
    SignPostEdit,
    SignPostUpVote,
    SignPostDownVote,
    CreateReserveStockpile,
    AccessReserveStockpile,
    RefreshReserveStockpiles,
    FullRepair,
    RegimentLeave,
    RegimentEdit,
    RegimentLink,
    RegimentDisband,
    DetachModularMount,
    Claim,
    ClaimWithPrompt,
    ClaimMulti,
    ClaimRefresh,
    ClaimRemove,
    Demolish,
    PackUp,
    DisconnectAll,
    FlagDisruptivePlacement,
    DrainPipes,
};

