#pragma once
#include "CoreMinimal.h"
#include "EBuildResponse.generated.h"

UENUM(BlueprintType)
enum class EBuildResponse : uint8 {
    Success,
    IsObstructed,
    IsObstructedByPlayer,
    IsObstructedByStructure,
    IsObstructedByVehicle,
    NotEnoughResources,
    NoBuildKit,
    Restricted,
    Error,
    RequiresVehicle,
    DoesntRequireVehicle,
    TechRequired,
    ComponentTechRequired,
    TownComponentTechRequired,
    SmallGarrisonRequired,
    LargeGarrisonRequired,
    MaxUpgradeReached,
    EnemyOwned,
    RequiresBlueprint,
    IsScorched,
    AsyncBuildRequested,
    FrontierBaseInvalidBorder,
    FrontierBaseCurrentZoneIsFriendly,
    FrontierBaseTooCloseToAnother,
    RequiresShovel,
    UpgradeRequirementsNotSatisfied,
    TooSteep,
    AdjacentToFortUpgrade,
    JoiningEnemyStructure,
    UpgradeFailedDueToDamage,
    ConnectorFailed,
    SignPostTooClose,
    SignPostRestricted,
    RequiresTownConnection,
    Claimed,
    EnemyBaseNearby,
    MustRemoveModifications,
    InvalidatesDependantStructureRequirements,
    TooManySameStructure,
    JoiningBurningStructure,
    NumTypes,
};

