#pragma once
#include "CoreMinimal.h"
#include "EFortModificationType.generated.h"

UENUM(BlueprintType)
enum class EFortModificationType : uint8 {
    Default,
    Door,
    FiringPort,
    BarbedWire,
    Bridge,
    Pipes,
    BunkBed,
    Lockers,
    Kitchen,
    Pantry,
    DishWashStation,
    Stove,
    Latrine,
    StrategicMap,
    RadioStation,
    Desk,
    Chalkboard,
    Module,
    Stairs,
    Sandbags,
    Ladder,
    TrenchRoof,
    InteriorFiringPort,
    RocketFactory,
    LargeShellFactory,
    ToolShed,
    SpecializedEquipment,
    PipeFabricator,
    Petrol,
    Fracker,
    Excavator,
    MaterialsSorter,
    Electric,
    SulfuricReactor,
    IndustrialTurbines,
    SteamTurbine,
    Forge,
    MetalPress,
    Smelter,
    BlastFurnace,
    EngineeringStation,
    Recycler,
    CokeFurnace,
    CoalLiquefier,
    AdvCoalLiquefier,
    Reformer,
    CrackingUnit,
    PetrochemicalPlant,
    MotorPool,
    ArtilleryFactory,
    LightVehicleAssembly,
    TankAssembly,
    WeaponsPlatformAssembly,
    TrainAssembly,
    HeavyTankAssembly,
    MachiningStation,
    AdvMachiningStation,
    Light,
    Count,
    None,
};

