#pragma once
#include "CoreMinimal.h"
#include "EPlacementStatus.generated.h"

UENUM(BlueprintType)
enum class EPlacementStatus : uint8 {
    Valid,
    Invalid,
    ValidFarFromOutpost,
    IsObstructed,
    BadFoundation,
    TooFarFromBuilder,
    TooCloseToEnemyTownHall,
    TooFarFromFriendlyTownHall,
    LimitReached,
    NotEnoughResources,
    TooCloseToBorder,
    TooFarFromBorder,
    ValidNotTunnelConnected,
    SurfaceNotSuitable,
    TooCloseToResourceField,
    FrontierBaseInvalidBorder,
    FrontierBaseCurrentZoneIsFriendly,
    FrontierBaseTooCloseToAnother,
    TooFarToDeploy,
    RequiresAttachment,
    TooSteep,
    TooFarFromLandscape,
    JoiningEnemyStructure,
    TooCloseToBridge,
    ConnectorNotConnected,
    SignPostTooClose,
    SignPostRestricted,
    ConnectorConfigurationInvalid,
    ConnectorTooLong,
    ConnectorTooShort,
    IsFloating,
    RequiresLinearAttachment,
    InUse,
    TooCloseToFieldBridge,
    ExtensionIsObstructed,
    ObstructsRoad,
    SplineTooSteep,
    TooManySameStructure,
    TooFarFromResourceField,
    TooManyNearResourceField,
    PathSocketTooClose,
    PathSocketTooCloseToEnd,
    PathSocketTooSteep,
    TooFarFromWater,
    TooFarFromFoundation,
    ConnectorRadiusInvalid,
    JoiningBurningStructure,
    StructureUnderLandscape,
    MustBeBuiltOnRailwayTrack,
    PathSocketTooCloseToBorder,
    TrackStartEndObstructsRoad,
    TrackCrossingRoadNotLevel,
    TooCloseToWater,
    SurfaceSamplesTooHigh,
    TooCloseToSameStructure,
    SurfaceSamplesAboveWater,
    SplineExtendsTooFarThroughBorder,
    TooCloseToEnemyTrack,
};

