#pragma once
#include "CoreMinimal.h"
#include "EShippableStatus.generated.h"

UENUM(BlueprintType)
enum class EShippableStatus : uint8 {
    Success,
    Error,
    NoShippable,
    NotShippable,
    RepairNeeded,
    ArmourNeeded,
    CargoInside,
    OccupantsInside,
    MustBePackaged,
    MustBeStanding,
    MustBeUnlocked,
    MustBeInSquad,
    CantPackageCargo,
    CantBeTravelling,
    TargetCantBeTravelling,
    InventoryMustBeEmpty,
    VehicleInventoryMustBeEmpty,
    TooClose,
    TooFar,
    AttachmentTooFar,
    PulleyTooFar,
    InvalidPlacement,
    CantPlaceInWater,
    OnUnstableGround,
    OnUnstableVehicle,
    CannotDeploy,
    CannotUndeploy,
    Frozen,
    MustDetachWeapon,
    MustDetachFromTrain,
    Reserved,
    ReservedExit,
    NoPower,
    Unsupported,
    UnsupportedRequest,
    UnsupportedSize,
    UnsupportedType,
    UnsupportedCodeName,
    InvalidState,
    NoShippables,
    MaxShippables,
    ObstructedByPackager,
    ObstructedByOther,
};

