#pragma once
#include "CoreMinimal.h"
#include "EWorldConquestMapId.generated.h"

UENUM(BlueprintType)
enum class EWorldConquestMapId : uint8 {
    Invalid,
    HomeRegionC,
    HomeRegionW,
    DeadLandsHex,
    CallahansPassageHex,
    MarbanHollow,
    UmbralWildwoodHex,
    MooringCountyHex,
    HeartlandsHex,
    LochMorHex,
    LinnMercyHex,
    ReachingTrailHex,
    StonecradleHex,
    FarranacCoastHex,
    WestgateHex,
    FishermansRowHex,
    OarbreakerHex,
    GreatMarchHex,
    TempestIslandHex,
    GodcroftsHex,
    EndlessShoreHex,
    AllodsBightHex,
    WeatheredExpanseHex,
    DrownedValeHex,
    ShackledChasmHex,
    ViperPitHex,
    Westgate,
    FishermansRowFCL,
    FoxholeFestivalMap,
    NevishLineHex,
    AcrithiaHex,
    RedRiverHex,
    CallumsCapeHex,
    SpeakingWoodsHex,
    BasinSionnachHex,
    HowlCountyHex,
    ClansheadValleyHex,
    MorgensCrossingHex,
    TheFingersHex,
    TerminusHex,
    KalokaiHex,
    AshFieldsHex,
    OriginHex,
    Count,
};

